import type { Metadata } from "next";
import { FaHome, FaMoneyBillWave, FaCheckCircle, FaCog } from "react-icons/fa";
import Image from "next/image";
import Separator from "@/components/Separator";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { text: "Home", href: "/Dashboard", icon: <FaHome /> },
  { text: "Expenses", href: "/Expense", icon: <FaMoneyBillWave /> },
  { text: "Approvals ", href: "/Approvals", icon: <FaCheckCircle /> },
  { text: "Settings", href: "/Settings", icon: <FaCog /> },
];

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex w-full h-screen text-gray-700">
      <aside className="w-[20%] p-2 border bg-white">
        {/* profile section */}
        <div className="flex flex-col justify-center items-center gap=4">
          <div className="rounded-full p-1 bg-green">
            <Image
              src={"/images/profile.png"}
              alt="adsf"
              width={100}
              height={100}
              className="object-contain w-[100px] h-[100px]"
            />
          </div>
          <span className="font-bold text-md">Aziel Randel Rabano</span>
        </div>

        {/* separator */}
        <Separator className="max-w-[90%] mx-auto mt-2 bg-gray-400" />

        {/* navs */}
        <nav className="flex flex-col justify-between items-start gap-8 px-24 mt-8">
          {navLinks.map((nav, index) => (
            <Link
              href={nav.href}
              key={index}
              className="flex items-center gap-8"
            >
              <span className="text-2xl">{nav.icon}</span>
              <span className="text-md font-medium">{nav.text}</span>
            </Link>
          ))}
        </nav>

        {/* logo */}
        <div></div>
      </aside>
      <div className="w-[80%] p-8 bg-white"> {children} </div>
    </div>
  );
}
